JuliaStats/DataArrays.jl

src/indexing.jl
=> Switch _div64, _mod64 for julia 0.4 changes

src/literals.jl, src/pooleddataarray.jl, test/broadcast.jl, test/data.jl, test/literals.jl, test/nas.jl, test/pooleddataarray.jl, test/reduce.jl, test/reducedim.jl, test/sort.jl
`@data` and `@pdata` were broken on 0.4. Other changes were just warnings.
=> Track Julia 0.4 Array literal changes

REQUIRE, src/DataArrays.jl
=> Reexport StatsBase.

src/DataArrays.jl
Fixes https://github.com/dcjones/Gadfly.jl/pull/667#issuecomment-133991074
=> Turn on precompilation

test/reducedim.jl
=> Fix reducedim test for cartesianmap->CartesianRange

src/reducedim.jl, test/data.jl
Use String instead of utf8 and stop using call.
=> A few extra adjustments to 0.5.

src/dataarray.jl, test/dataarray.jl
Corrected PR JuliaStats/DataArrays.jl#189.
=> Check for NA in DataArray inner constructor

src/extras.jl, test/extras.jl
Rebase of https://github.com/JuliaStats/DataArrays.jl/pull/155.
=> repeat() methods for DataArray and PooledDataArray

src/reduce.jl, src/reducedim.jl
This reduces code duplication and also seems to be faster.
=> Remove varzm and just use varm with m=0.

src/extras.jl, src/reducedim.jl
Minor changes. I'll merge when green such that we can have a version tagged.
=> Change bitpack to BitArray and break a line.

REQUIRE, src/broadcast.jl
Needed due to pending JuliaLang/julia#17398. However, requires a version of Compat tagged that includes https://github.com/JuliaLang/Compat.jl/pull/252, tentatively assumed to be 0.8.6, hence WIP at the moment.
=> Replace eltype_plus with promote_eltype_op

.travis.yml, README.md, appveyor.yml
I also added the 0.5 PkgEvaluator badge because it was missing.
=> Update CI to use 0.5 as a release

src/operators.jl, src/pooleddataarray.jl, test/broadcast.jl
* Use tuple type instead of tuples (Ref https://github.com/JuliaLang/julia/pull/18444 and it's easier to infer in general)
=> Fix use of `invoke`

src/abstractdataarray.jl, test/nas.jl
=> fix anyna and allna

src/predicates.jl
isprime() has been moved to Primes from Base.
Ref: https://github.com/JuliaStats/DataArrays.jl/issues/226
=> Update predicates.jl for function isprime()

README.md
[ci skip] <-- apparently Travis didn't notice that
=> Replace 0.3 PkgEval badge with 0.6

.gitignore, .travis.yml, README.md, docs/make.jl, docs/src/da.md, docs/src/index.md, docs/src/util.md, src/abstractdataarray.jl, src/dataarray.jl, src/datavector.jl, src/extras.jl, src/literals.jl, src/natype.jl, src/pooleddataarray.jl, src/statistics.jl
This PR converts the many structured comments to actual docstrings as appropriate, with the overall goal of making full documentation for the package.
To-do list:
There are more files in this repo than I remembered.
=> RFC: The Great Doc-ening

README.md, src/indexing.jl
Let's see if this breaks anything.
=> Don't overload unsafe_getindex with Base types

REQUIRE, src/statistics.jl, test/statistics.jl
Follows https://github.com/JuliaStats/StatsBase.jl/pull/247
=> Move describe functions for DataArrays from DataFrames to DataArrays

src/operators.jl
Use the merge commit.
Cf. https://github.com/JuliaStats/DataArrays.jl/pull/259#discussion_r119043312
=> Fix VERSION check

REQUIRE, src/DataArrays.jl, src/reducedim.jl
=> Use generated functions instead of @ngenerate macro

src/pooleddataarray.jl, test/pooleddataarray.jl
See https://github.com/JuliaStats/DataArrays.jl/issues/273 .
=> Fix MethodError when calling groupby, unstack, etc

src/reducedim.jl
if this is still an improvement in performance, it should be done in Base, not here
=> delete _mapreducedim! method on Base types

REQUIRE, src/dataarray.jl, src/deprecated.jl, src/pooleddataarray.jl, src/statistics.jl, test/data.jl, test/dataarray.jl, test/nas.jl, test/newtests/dataarray.jl, test/pooleddataarray.jl, test/reduce.jl, test/sort.jl
=> Use skipmissing() instead of Missings.skip()
