JuliaStats/DataArrays.jl

- src/dataarray.jl
- src/deprecated.jl
- src/pooleddataarray.jl
- test/conversions.jl
- test/data.jl
- test/datamatrix.jl
- test/newtests/dataarray.jl
This is just a rebased change from #108. Moved `array()` stuff into deprecated but otherwise didn't change the PR.
> Replace array with Base.convert

- src/indexing.jl
There were a few internal APIs that I changed in JuliaLang/julia#10525.  This is a start at fixing some of your uses of them.  ~~I think I got everything except a few assumptions about how Base.checkbounds will work with NAType, so this fails in a few places where you expect checkbounds to throw an NAException -- it is now a MethodError.~~
There is a lot more that you could do to adjust to a post-10525 world.  Let me know if you have any questions along the way.
> Internal API changes due to 10525

- src/pooleddataarray.jl
- test/pooleddataarray.jl
Avoid slow `setindex!(PooledDataArray)` (see #105) by permuting `.refs` only. This should speed up data frame sorting.
PR redefines `Base.permute!!()`, which is not exported by `Base`. The reason is that `permute!(v, p)` calls `permute!!(v, copy(p))`, but `DataFrames` uses `permute!!()` directly to avoid unnecessary temporary array allocation for each column.
> Speed up permute!(PooledDataArray)

- src/dataarray.jl
It significantly reduces memory allocation overhead in `DataFrames` for me on 0.4.
> isna() for scalar case

- src/indexing.jl
Update the index checkbounds API to the latest incarnation from https://github.com/JuliaLang/julia/pull/11895.  It's now documented, so if anyone dares touch it again they'll have to provide a deprecation path.
Sorry for repeatedly lowering your coverage metrics here.  Give it some time and I'm sure you'll be able to drop the middle definition after 0.4 has been out for a while.
> Yet another checkbounds code churn

- src/broadcast.jl
- src/datavector.jl
- src/deprecated.jl
- src/extras.jl
- src/indexing.jl
- src/natype.jl
- src/operators.jl
- src/reduce.jl
- src/reducedim.jl
- src/sort.jl
- test/extras.jl
- test/literals.jl
- test/newtests/dataarray.jl
- test/reducedim.jl
- test/runtests.jl
Union(..) -> Union{..}, String -> AbstractString, FloatingPoint -> AbstractFloat
The two remaining messages are:
1. cartesianmap
2. {..} syntax (Note: replacing with Any[..] fails
> Fix 0.4 deprecations

- src/broadcast.jl
I'm not sure how much of these can go to `Compat.jl` so I just implement everything here....
c.c. @timholy 
Ref JuliaLang/julia#13803
> Fix breakage on 0.5-dev.

- .travis.yml
- REQUIRE
- src/DataArrays.jl
- src/abstractdataarray.jl
- src/broadcast.jl
- src/dataarray.jl
- src/datavector.jl
- src/extras.jl
- src/indexing.jl
- src/natype.jl
- src/operators.jl
- src/pooleddataarray.jl
- src/reduce.jl
- src/reducedim.jl
- test/broadcast.jl
- test/data.jl
- test/dataarray.jl
- test/datamatrix.jl
- test/literals.jl
- test/nas.jl
- test/operators.jl
- test/reduce.jl
- test/reducedim.jl
All kind of stuff: new indexing, new iterations, no functors, new `getfield` syntax for operators, string changes and some other deprecations. Tests are passing now on master but the string story is not completely settled yet in `Compat.jl` so we'll need a new tag there before tests pass on 0.4. It might also be the right time to stop 0.3 support. I don't want to spend much time on making the tests pass there.
I should also mention that some of the tests are now slower than they are on 0.4. However, it's difficult to say if this is because of my changes here or because of the general slowdown on master. I profiled the `reducedim` tests and there is spent a lot of time in `inference` (even after the first run) and I can figure out why.
> Make DataArrays ready for 0.5

- appveyor.yml
I think there may be a test failure on Windows at the moment - can someone turn AppVeyor on for this repo on their account? For people with commit access the AppVeyor site should handle enabling the webhook, but if it doesn't work then I can dig up specific instructions.
> enable AppVeyor

- src/dataarray.jl
Even standard Arrays use that method, which is designed to be more
efficient.
> Use hash method for AbstractArray to fix test failure on 32-bit Windows

- src/dataarray.jl
- src/datavector.jl
now removed in 0.5 - defining these wasn't giving deprecation warnings,
but calling them should have been?
> remove methods that are deprecated in Base

- src/broadcast.jl
- src/operators.jl
- src/reduce.jl
- test/operators.jl
- test/reduce.jl
- test/reducedim.jl
This fixes support for cases in which the return type is different
from the inputs, in particular Date. Also makes handling of /
a bit less of a special case.
Fixes https://github.com/JuliaStats/DataFrames.jl/issues/987.
> Use Base.promote_op() for arithmetic operators

- src/pooleddataarray.jl
This now triggers a failure on 0.5, since concatenation does not happen.
> Fix deprecated concatenation syntax

- src/extras.jl
- test/extras.jl
In Julia 0.5 and in Compat.jl, repeat() accepts any iterable
argument, in particular scalars. The restriction triggers an
error in DataFrames on Julia 0.5.
> Loosen type signature for repeat()

- src/pooleddataarray.jl
- test/pooleddataarray.jl
Currently the type signature of setlevels! is extremely strict and it would be best to allow the user some more flexibility. This should also fix Gadfly's tests being broken (at least on 0.4).
See #201
> add a less specific version of setlevels!; fixes #201 and tests on Gadfly.jl

- src/extras.jl
```
WARNING: [a] concatenation is deprecated; use collect(a) instead
in depwarn at deprecated.jl:73
in oldstyle_vcat_warning at ./abstractarray.jl:29
in cut at .../.julia/v0.4/DataArrays/src/extras.jl:64
```
> Fix concat deprecation warning in `cut`

- src/broadcast.jl
- src/indexing.jl
trying to work around OneTo issue on nightly
> RFC: work around MethodErrors with Base.OneTo

- src/broadcast.jl
`promote_eltype` is defined in `abstractarray.jl` in Base. Also, this will avoid problems if https://github.com/JuliaLang/julia/pull/17389 were to be merged.
> Reorganize imports in broadcast.jl

- src/pooleddataarray.jl
This error is never shown because it raises another error instead, namely that no matching constructor of ErrorException was found.
Also, int is deprecated in favour of Int.
> ErrorException doesn't take multiple arguments, but error does

- src/dataarray.jl
- test/conversions.jl
Simple test that previously caused an error:
> convert (DataArray{Integer,1},DataArray(Any,2))
That might seem pointless but consider this:
> a = DataArray(Any,2)
> a[1] = 2;
> a[2] = NA;
> convert(DataArray{Integer,1},a)
All values are defined, but the conversion still failed. This commit fixes this.
> An uninitialized DataArray is now convertable.

- src/pooleddataarray.jl
- test/pooleddataarray.jl
This feature could then be used to fix vcat of pooled columns in DataFrames as well, https://github.com/JuliaStats/DataFrames.jl/pull/990
> vcat of PooledDataVector might need to expand the reftype

- src/pooleddataarray.jl
The latter is provided in Julia Base whiel the former is deprecated in
StatsBase. Note that findat() returns the first matching index, but
indexin() the last one. Here it doesn't matter since pools only contains unique
values. Also remove an unnecessarily complex myunique() definition.
Fixes breakage (and warnings) introduced by incorrect deprecation in StatsBase. Cf. https://github.com/JuliaLang/METADATA.jl/pull/6660#issuecomment-252338632.
> Replace calls to findat() with calls to indexin()

- test/reducedim.jl
I think the backporting in https://github.com/JuliaLang/julia/pull/19103 broke the tests on 0.5.
> Fix reducedim tests for backports to 0.5

- test/reducedim.jl
This reverts commit 4f5d706fad4030bfb3c7975622c2b8200611074d.
The changes shouldn't be necessary and might break when 0.5.1 is released.
> Revert "Fix reducedim tests for backports to 0.5"

- test/abstractarray.jl
- test/booleans.jl
- test/broadcast.jl
- test/constructors.jl
- test/containers.jl
- test/conversions.jl
- test/data.jl
- test/dataarray.jl
- test/datamatrix.jl
- test/extras.jl
- test/indexing.jl
- test/linalg.jl
- test/literals.jl
- test/nas.jl
- test/operators.jl
- test/padding.jl
- test/pooleddataarray.jl
- test/reduce.jl
- test/reducedim.jl
- test/runtests.jl
- test/sort.jl
- test/statistics.jl
This PR restructures the tests to use `@testset` and `@test` rather than wrapping units of tests in modules and checking correctness with `@assert`.
> Update tests to use testsets

- docs/src/da.md
- src/DataArrays.jl
- src/abstractdataarray.jl
- src/dataarray.jl
- src/deprecated.jl
- src/indexing.jl
- src/pooleddataarray.jl
- src/reduce.jl
- test/nas.jl
- test/operators.jl
- test/reducedim.jl
Rather than defining new functions `anyna` and `allna`, this PR extends `Base.any` and `Base.all` with `isna` to achieve the same thing.
> Deprecate anyna(x) in favor of any(isna, x) (same for allna)

- test/reduce.jl
Ref discussion in https://github.com/JuliaStats/StatsBase.jl/pull/248
> Remove a problematic test case that we do not want to support

- src/dataarray.jl
The deprecation wasn't used as the varargs isa(::DataArray, ::Real...) method
unexpectedly took precedence. It shouldn't apply when there are zero indices,
so change its signature to reflect this.
Get rid of the @nsplat call which isn't needed here (and no longer used in
Julia Base).
-------------
This is a possibly cleaner alternative to https://github.com/JuliaStats/DataArrays.jl/pull/251. I don't understand why `@nsplat` was used here, but AFAICT we can remove it now since the function is so simple.
> Fix isna(::DataArray) deprecation (alternate take)

- src/operators.jl
There has been some change to Julia in the macrocall AST, adding the LineNumberNode.
Unless there is another change to Julia, some packages using `:macrocall` expression generation will break.
> Add missing LineNumberNode to @swappable call (fixes #257)

- test/booleans.jl
Test framework expects a pass/fail boolean from a test expression, but `==` can have NA value. Therefore it might be appropriate to use `===` in these cases. In fact, it might be smart to use `===` in all tests and packages when comparing an expression to a boolean value.
> Use === for booleans when == is overloaded

- src/operators.jl
- src/pooleddataarray.jl
- test/operators.jl
- test/pooleddataarray.jl
Use the number of observed values (plus one for `NA`) to determine the
length of the result of `unique` on `PooledDataArrays`.
Fixes #265
> Fix uninitialised values in unique for PooledDataArray

- src/deprecated.jl
- src/operators.jl
- test/runtests.jl
This should fix the ambiguity error that occurs when attempting to `&`, `|`, or `xor` two `DataArray`s. This also deprecates that functionality in favor of dot `broadcast`. To top it off, I've added ambiguity detection to the tests.
cc @nalimilan, I think this is what you were running into in DataFramesMeta.
> Fix bitwise operator ambiguities, test for ambiguities, deprecate vectorized ops

- REQUIRE
- benchmark/operators.jl
- src/broadcast.jl
- src/deprecated.jl
- src/extras.jl
- src/operators.jl
- src/reducedim.jl
- test/newtests/dataarray.jl
This change ~~removes the dependency on Compat (which was actually unused),~~ updates the type definition syntax to `struct`, and bumps the required Julia version from a 0.6 prerelease to 0.6 release.
> Minor 0.6 cleanup

- src/datavector.jl
- test/dataarray.jl
This ensures that we get the correct element type, among other things. Fixes #276.
> Use the default Base implementation of map

- src/dataarray.jl
- test/dataarray.jl
> Don't allocate new memory in convert when element type is unchanged

- src/abstractdataarray.jl
- src/broadcast.jl
- src/dataarray.jl
- src/extras.jl
- src/natype.jl
- src/operators.jl
- src/pooleddataarray.jl
- src/reduce.jl
- src/reducedim.jl
- src/statistics.jl
- test/broadcast.jl
- test/constructors.jl
- test/data.jl
- test/dataarray.jl
- test/extras.jl
- test/nas.jl
- test/runtests.jl
As discussed on Slack. It was actually not that bad. The core changes are in `abstractdataarray.jl` and defines
```julia
abstract type AbstractDataArray{T, N} <: AbstractArray{Union{T,NAtype}, N} end
Base.eltype{T, N}(d::AbstractDataArray{T, N}) = Union{T,NAtype}
```
So for subtypes of `AbstractDataArray`, the `T` is not referring to union but for signatures using `AbstractArray` the `T` refers to the union. This requires a little care when we ping-ping between Base and DataArrays definitions such as `broadcast` and `similar`. For that, it was convenient to define an `extractT` function to return the `T` part of a `Union{T,NAtype}`.
The changes here also require some changes to `DataFrames`. Hopefully, I'll be able to open a PR with them tomorrow and then we can look at the whole picture. …
> RFC: Stop lying about eltype

- README.md
- docs/src/index.md
- src/pooleddataarray.jl
Recommend either CategoricalArrays (for categorical data) or PooledArrays (for compressed storage) as replacements. Do not ajust tests for now.
> Deprecate PooledDataArray

- REQUIRE
- src/DataArrays.jl
- src/broadcast.jl
- src/dataarray.jl
- src/datavector.jl
- src/deprecated.jl
- src/indexing.jl
- src/linalg.jl
- src/literals.jl
- src/operators.jl
- src/pooleddataarray.jl
- src/reducedim.jl
- test/data.jl
- test/dataarray.jl
- test/operators.jl
- test/runtests.jl
Fixes various deprecation warnings and some errors that prevent DataArrays from precompiling on 0.7 while maintaining compatibility with 0.6.
This is a WIP because I'm waiting for a new Compat version to be released to fix the `ipermute!` -> `invpermute!` error.
> Fix miscellaneous deprecations for latest Julia 0.7

- src/reduce.jl
- src/reducedim.jl
- test/reduce.jl
- test/reducedim.jl
These have been deprecated in Julia 0.6, and removed in 0.7. The deprecation uses sum, minimum and maximum, so no replacement is needed.
This allows loading the package on recent Julia 0.7.
> Remove sumabs, sumabs2, maxabs and minabs
